### ISSUE TITLE
Symbolic links are not followed

### ISSUE THREAD

**Issue by Al-** [gkiefer/backup2l#23]
Backing up does not follow symbolic links as the default behaviour of 'find' is option -P. This might be unexpected to the average user (who realizes this only when the data is lost). I suggest to mention this in the man page and also in the explanations in backup2l.conf. Maybe also mention that option -L may be provided in SRCLIST to force find (and thus backup2l) follow symbolic links.

**Comment by gkiefer** [comment]
Thank you for the feedback!

Symbolic links generally point to files that are reachable elsewhere, namely by their original path. Following symlinks by default may cause duplication, the risk of infinite dereferencing loops and inconsistencies paired with data loss if a file is modified during backup. All this may also be unexpected and unwanted to the users, so that the default behavior intentionally is to not follow symbolic links.

I added a clarification to the man page and 'first-time.conf'.

Resolved in d74f8c56e0197eb19be44d7f5aa0eca86b8496e4 .
